# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry and the export plugin for pip
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry poetry-plugin-export
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      - poetry export -f requirements.txt --without-hashes --only docs -o only-docs.txt
      - pip install --requirement only-docs.txt

mkdocs:
  configuration: mkdocs.yml
