Mutelist:
  Accounts:
    "*":
      ########################### AWS CONTROL TOWER ###########################
      ### The following entries includes all resources created by AWS Control Tower when setting up a landing zone ###
      # https://docs.aws.amazon.com/controltower/latest/userguide/how-control-tower-works.html #
      Checks:
        "*":
          Regions:
            - "*"
          Resources:
            - "*"
