# AWS EC2 Configuration
# aws.ec2_elastic_ip_shodan
shodan_api_key: null
# aws.ec2_securitygroup_with_many_ingress_egress_rules --> by default is 50 rules
max_security_group_rules: 50
# aws.ec2_instance_older_than_specific_days --> by default is 6 months (180 days)
max_ec2_instance_age_in_days: 180

# AWS VPC Configuration (vpc_endpoint_connections_trust_boundaries, vpc_endpoint_services_allowed_principals_trust_boundaries)
# Single account environment: No action required. The AWS account number will be automatically added by the checks.
# Multi account environment: Any additional trusted account number should be added as a space separated list, e.g.
# trusted_account_ids : ["123456789012", "098765432109", "678901234567"]
trusted_account_ids: []

# AWS Cloudwatch Configuration
# aws.cloudwatch_log_group_retention_policy_specific_days_enabled --> by default is 365 days
log_group_retention_days: 365

# AWS AppStream Session Configuration
# aws.appstream_fleet_session_idle_disconnect_timeout
max_idle_disconnect_timeout_in_seconds: 600 # 10 Minutes
# aws.appstream_fleet_session_disconnect_timeout
max_disconnect_timeout_in_seconds: 300 # 5 Minutes
# aws.appstream_fleet_maximum_session_duration
max_session_duration_seconds: 36000 # 10 Hours

# AWS Lambda Configuration
# aws.awslambda_function_using_supported_runtimes
obsolete_lambda_runtimes:
  [
    "python3.6",
    "python2.7",
    "nodejs4.3",
    "nodejs4.3-edge",
    "nodejs6.10",
    "nodejs",
    "nodejs8.10",
    "nodejs10.x",
    "dotnetcore1.0",
    "dotnetcore2.0",
    "dotnetcore2.1",
    "ruby2.5",
  ]

# AWS Rds Configuration
# aws.awsrds_instance_using_supported_engine_version
# SQL
supported_rds_engines_mysql:
  [
    "8.0",
    "8.0.32",
    "8.0.31",
    "8.0.30",
    "8.0.28",
    "8.0.27",
    "8.0.26",
    "8.0.25",
    "8.0.23",
    "5.7",
    "5.7.41",
    "5.7.40",
    "5.7.39",
    "5.7.38",
    "5.7.37",
    "5.7.36",
    "5.7.34",
    "5.7.33",
  ]

# MariaDB
supported_rds_engines_madiadb:
  [
    "10.6.",
    "10.6.12",
    "10.6.11",
    "10.6.10",
    "10.6.8",
    "10.6.7",
    "10.6.5",
    "10.5",
    "10.5.19",
    "10.5.18",
    "10.5.17",
    "10.5.16",
    "10.5.15",
    "10.5.13",
    "10.5.12",
    "10.4",
    "10.4.28",
    "10.4.27",
    "10.4.26",
    "10.4.25",
    "10.4.24",
    "10.3",
    "10.3.38",
    "10.3.37",
    "10.3.36",
    "10.3.35",
    "10.3.34",
  ]

#PostgreSQL
supported_rds_engines_postgres:
  [
    "15",
    "15.2",
    "14",
    "14.7",
    "14.6",
    "14.5",
    "14.4",
    "14.3",
    "14.2",
    "14.1",
    "13",
    "13.10",
    "13.9",
    "13.8",
    "13.7",
    "13.6",
    "13.5",
    "13.4",
    "13.3",
    "12",
    "12.14",
    "12.13",
    "12.12",
    "12.11",
    "12.10",
    "12.9",
    "12.8",
    "12.7",
    "11.19",
    "11.18",
    "11.17",
    "11.16",
    "11.15",
    "11.14",
    "11.13",
    "11.12",
    "10.23",
    "10.22",
    "10.21",
    "10.20",
    "10.19",
    "10.18",
    "10.17",
  ]

# AWS Organizations
# organizations_scp_check_deny_regions
# organizations_enabled_regions: [
#   'eu-central-1',
#   'eu-west-1',
#   "us-east-1"
# ]
organizations_enabled_regions: []
# organizations_delegated_administrators
# organizations_trusted_delegated_administrators: [
#   "12345678901"
# ]
organizations_trusted_delegated_administrators: []
