name: linters

on: [push]

env:
  - TRUFFLEHOG_VERSION: v3.4.4
  
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@${{ env.TRUFFLEHOG_VERSION }}
  