name: find-secrets

on: push

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.4.4
