# This is a basic workflow to help you get started with Actions

name: Refresh regions of AWS services

on:
  push:
    branches:
      - "PRWLR-609-services-parse-aws-services-json-and-add-to-github-actions"
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

env:
  GITHUB_BRANCH: "PRWLR-609-services-parse-aws-services-json-and-add-to-github-actions"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_BRANCH }}

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python3 util/update_aws_services_regions.py

      # Create pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat(regions_update): Update regions for AWS services."
          branch: "aws-services-regions-updated"
          labels: "feature, automated pr"
          title: "feat(regions_update): Changes in regions for AWS services."
          body: "This PR updates the regions for AWS services."
